name = "dailytally"
main = "worker.js"
compatibility_date = "2026-04-27"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "dailytally"
database_id = "0ebc08db-cb6b-466a-9e0f-a6904f6626ed"
migrations_dir = "migrations"
